cblt/urls.py
from django.views.defaults import page_not_found
from django.conf.urls import patterns, include, url
from django.conf import settings
from django.contrib import admin
from django.views.generic import TemplateView, RedirectView

from .sitemap import sitemaps

from filebrowser.sites import site



# admin.autodiscover()

urlpatterns = patterns('',
    url(r'^$', 'cblt.views.home', name='home'),
    url(r'^beta-home/$', 'cblt.views.home2', name='beta-home'),
    # url(r'^', include('debug_toolbar_htmltidy.urls')),
    url(r'^sitemap\.xml$', 'django.contrib.sitemaps.views.sitemap', {'sitemaps': sitemaps}),
    url(r'^robots\.txt$', TemplateView.as_view(template_name="robots.txt", content_type='text/plain')),
    url(r'^newsletter/', include('newsletter.urls')),
    url(r'^coming-soon$', TemplateView.as_view(template_name='coming-soon.html'), name='coming-soon'),
    url(r'^home2$', 'cblt.views.home2',url(r'^admin/filebrowser/', include(site.urls)), name='home2'),
    url(r'^about-our-website$', 'cblt.views.about', name='about'),
    url(r'^our-opinions', 'cblt.views.our_opinions', name='our_opinions'),
    #Manage Property
    url(r'^manage-properties$', 'cblt.views.manage_property', name='manage_property'),
    url(r'^laketahoe-directory$', 'cblt.views.list_directory', name='laketahoe-directory'),
    url(r'^contact-us$', 'cblt.views.contact_us', name='contact_us'),
    url(r'^ajax-contact-us/$', 'cblt.views.ajax_contact_us'),
    #url(r'^bio/', 'cblt.views.bio', name='bio'),
    # Uncomment the admin/doc line below to enable admin documentation:
    # url(r'^admin/doc/', include('django.contrib.admindocs.urls')),

    # Uncomment the next line to enable the admin:
    url(r'^tinymce/', include('tinymce.urls')),
    url(r'^blog/(?P<content_id>\d+)/(?P<content_slug>[\w-]+)$', 'mls.views.content_page', name='content_page'),
    url(r'^blog/filter/(?P<location_type_id>\d+)/(?P<location_type_slug>[\w-]+)$', 'mls.views.filter_content', name='filter_content'),
    url(r'^blog$', 'mls.views.blog', name='blog'),
    url(r'^admin/', include(admin.site.urls)),
    url(r'^admin/filebrowser/', include(site.urls)),
    url(r'^accounts/', include('allauth.urls')),
    url(r'^mls/', include('mls.urls')),
    #url(r'^search-mls', TemplateView.as_view(template_name='search_all.html'), name='search_all'),
    #url(r'^detailed-property/(?P<mls_no>\d+)/$', 'detailed_property', name='detailed_property'),
    url(r'^photologue/', include('photologue.urls')),

    #realestate new urls
    url(r'^realestate/search$', 'mls.views.search_result', name='search_result'),
    url(r'^realestate/explore$', 'mls.views.explore', name='explore'),
    url(r'^realestate/statistics$', 'mls.views.statistics', name='statistics'),
    url(r'^realestate/price-reductions$', 'mls.views.price_reductions', name='price_reductions'),
    url(r'^realestate/sold', 'mls.views.sold', name='sold'),
    url(r'^realestate/under-contract', 'mls.views.under_contract', name='under_contract'),
    url(r'^realestate/communities$', 'mls.views.communities', name='realestate_communities'),
    url(r'^realestate/city$', 'mls.views.cities', name='realestate_cities'),
    url(r'^realestate/neighborhood$', 'mls.views.neighborhood', name='realestate_neighborhood'),
    url(r'^realestate/latest-listings$', 'mls.views.latest_listings', name='latest_listings'),
    # url(r'^realestate/listing/(?P<mls_no>\d+)/edit$', 'mls.views.edit_redirect', name='detailed_property_edit'),
    url(r'^realestate/listing/(?P<mls_no>\d+)$', 'mls.views.detailed_property_redirect'),
    url(r'^realestate/city/(?P<city_slug>[\w-]+)$', 'mls.views.view_city', name='view_city'),
    url(r'^realestate/neighborhood/(?P<area_slug>[\w-]+)$', 'mls.views.view_area', name='view_area'),
    url(r'^realestate/setting/(?P<setting_slug>[\w-]+)$', 'mls.views.view_setting', name='view_setting'),
    url(r'^realestate/(?P<community_slug>[\w-]+)$', 'mls.views.view_community', name='view_community'),
    url(r'^realestate/(?P<community_slug>[\w-]+)/(?P<area_slug>[\w-]+)/mls-(?P<mls_no>\d+)-(?P<address_slug>[\w-]+)$', 'mls.views.detailed_property', name='detailed_property'),
    url(r'^realestate/(?P<community_slug>[\w-]+)/(?P<area_slug>[\w-]+)/(?P<mls_no>\d+)/edit$', 'mls.views.edit_redirect', name='detailed_property_edit'),
    url(r'^realestate/(?P<community_slug>[\w-]+)/(?P<area_slug>[\w-]+)/(?P<mls_no>\d+)$', 'mls.views.property_redirect'),
    url(r'^lakefronts$', RedirectView.as_view(url='/realestate/setting/lakefront')),
    url(r'^(?P<mls_no>\d+)$', 'mls.views.detailed_property_redirect_2'),
    url(r'^(?P<fuzzy_slug>[\w-]+)$', 'mls.views.fuzzy_redirect', name='fuzzy_redirect'),

    #Vendor 
    url(r'^realestate/vendors/(?P<pk>\d+)$', 'mls.views.detailed_vendor', name="detailed_vendor"),
    url(r'^realestate/related-contents/$', 'mls.views.property_related_content', name="related_contents"),
    url(r'^404/$', 'django.views.defaults.page_not_found', ),
)

if settings.DEBUG:
    urlpatterns += patterns('',
        (r'^media/(?P<path>.*)$', 'django.views.static.serve', {'document_root': settings.MEDIA_ROOT}),
        (r'^static/(?P<path>.*)$', 'django.views.static.serve', {'document_root': settings.STATIC_ROOT}),
    )

mls/urls.py
from django.conf.urls import *


urlpatterns = patterns('mls.views',
    #url(r'^$', 'listing_index', name='listing_index'),
    url(r'^ajax-contact-us/$', 'ajax_contact_us'),
    #url(r'^detailed-property/(?P<mls_no>\d+)/$', 'detailed_property', name='detailed_property'),
    #url(r'^featured-property$', 'featured_property', name='featured_property'),
    #url(r'^compare-property$', 'compare_property', name='compare_property'),

    #url(r'^search/luxury$', 'luxury_properties', name='luxury_properties'),
    #community
    #url(r'^search/community$', 'community', name='community'),
    #url(r'^search/community/(?P<community_slug>[\w-]+)$', 'view_community', name='view_community'),
    url(r'^search/community/(?P<community_slug>[\w-]+)$', 'redirect_community', name='redirect_community'),
    #city
    #url(r'^search/city$', 'city', name='city'),
    url(r'^search/city/(?P<city_slug>[\w-]+)$', 'redirect_city', name='redirect_city'),
    #area
    #url(r'^search/area$', 'area', name='area'),
    #url(r'^search/area/(?P<area_slug>[\w-]+)$', 'view_area', name='view_area'),
    #setting
    #url(r'^search/setting$', 'setting', name='setting'),
    url(r'^search/setting/(?P<setting_slug>[\w-]+)$', 'redirect_setting', name='redirect_setting'),
    #search
    #url(r'^search/', include('haystack.urls')),
    #url(r'^search$', 'search_result', name='search_result'),
    #url(r'^request-info/(?P<mls_no>\d+)$', 'request_info', name='request_info'),
    #statistics
    # url(r'^statistics$', 'statistics', name='statistics'),
    #url(r'^price-reductions$', 'price_reductions', name='price_reductions'),
    #url(r'^sold$', 'sold', name='realestate_sold'),

)

cblt/models.py
from django.db.models.signals import class_prepared

def longer_username(sender, *args, **kwargs):
    # You can't just do `if sender == django.contrib.auth.models.User`
    # because you would have to import the model
    # You have to test using __name__ and __module__
    if sender.__name__ == "User" and sender.__module__ == "django.contrib.auth.models":
        sender._meta.get_field("username").max_length = 75

class_prepared.connect(longer_username)

cblt/forms.py
from django import forms

class ContactUsForm(forms.Form):
    name = forms.CharField(widget=forms.TextInput(attrs={'class':'text'}),
                                 error_messages={'required': 'Please enter your name.'}, required=True, max_length=100)
    email = forms.EmailField(widget=forms.TextInput(attrs={'class':'text'}), \
                                error_messages={'required': 'Please enter your email address','invalid': 'Invalid email address'}, \
                                required=True, max_length=100)
    phone = forms.CharField(widget=forms.TextInput(attrs={'class':'text'}),
                                required=False, max_length=100)
    message = forms.CharField(widget=forms.Textarea(), error_messages={'required': 'Please enter a message.'}, required=True)

cblt/views.py
from cblt.utils import get_map_details, get_years_of_data
from datetime import datetime
from django.core.mail.message import EmailMultiAlternatives
from django.db.models import Q
from django.http import HttpResponse
from django.utils import simplejson
from django.contrib import messages
from django.conf import settings
from django.shortcuts import render_to_response
from django.template import RequestContext
from django.template.loader import render_to_string
from django.utils.html import strip_tags
import cblt.mdetect as mdetect
from cblt.forms import ContactUsForm
from mls.models import Listing, SellerComment, PriceChange, SiteContent, BigTable,PropertyManagement,BusinessDirectory
from mailer import send_html_mail


today = datetime.today()


def home(request, template='home3.html', context={}):
    '''
        For CBLakeTahoe HOME PAGE 
    '''

    active = Listing.objects.select_related('C_Community', 'C_City', 'img_set',)\
                            .filter(C_Status__name='ACTIVE')\
                            .exclude(Q(C_Community__name='SurroundingArea')
                                    |Q(C_Community__name='Sierra County'))\
                            .order_by('-C_LstDate')\
                            .only('C_LstDate', 'C_Community', 'C_NoBeds', 'C_SqFeet', 'C_AskPrice','C_Address',
                                      'C_MLSNo', 'C_NoBeds', 'C_NoBaths1', 'C_Garage', 'C_SqFeet', 'C_YrBlt',
                                      'C_AcresNo', 'C_LotDims', 'C_City', 'C_GeoLat', 'C_GeoLong')[:5]

    try:
        price_change = BigTable.objects.get(function='price_reduced', scope='All')
    except BigTable.DoesNotExist:
        price_change = BigTable.objects.none()
    lakefronts = Listing.objects.select_related('C_Community', 'C_City', 'img_set',)\
                        .filter(C_Status__name='ACTIVE', C_Setting__slug='lakefront', \
                                C_AskPrice__gte=2000000).order_by('-C_LstDate')[:6]

    context.update({
        'active': active, 'price_change':price_change,
        'lakefronts': lakefronts, 'modal_should_load':False
        })



    if not request.session.get('modal_has_loaded'):
        request.session['modal_has_loaded'] = True
        context['modal_should_load'] = True

    user_agent = request.META.get("HTTP_USER_AGENT")
    http_accept = request.META.get("HTTP_ACCEPT")

    if user_agent and http_accept:
        agent = mdetect.UAgentInfo(userAgent=user_agent, httpAccept=http_accept)
        is_tablet = agent.detectTierTablet()
        is_phone = agent.detectTierIphone()
        is_mobile = is_tablet or is_phone or agent.detectMobileQuick()

        if is_mobile:
            context['modal_should_load'] = False
    years_of_data = get_years_of_data()
    context['seo_tags'] = {}
    #context['seo_tags']['description'] = "We custom built this website. Our opinions of the homes, more data/stats, "+ years_of_data +" yrs of sales for comps. A very unique Lake Tahoe real estate website"
    context['seo_tags']['description'] = 'CB Lake Tahoe - more real estate data/stats. A unique resource for Truckee and Lake Tahoe real estate information'
    return render_to_response(template, context, context_instance=RequestContext(request))


def home2(request, template='home3.html', context={}):

    active = Listing.objects.select_related('C_Community', 'C_City', 'img_set',)\
                            .filter(C_Status__name='ACTIVE')\
                            .exclude(Q(C_Community__name='SurroundingArea')
                                    |Q(C_Community__name='Sierra County'))\
                            .order_by('-C_LstDate')\
                            .only('C_LstDate', 'C_Community', 'C_NoBeds', 'C_SqFeet', 'C_AskPrice','C_Address',
                                      'C_MLSNo', 'C_NoBeds', 'C_NoBaths1', 'C_Garage', 'C_SqFeet', 'C_YrBlt',
                                      'C_AcresNo', 'C_LotDims', 'C_City', 'C_GeoLat', 'C_GeoLong')[:5]

    price_change = BigTable.objects.get(function='price_reduced', scope='All')
    lakefronts = Listing.objects.select_related('C_Community', 'C_City', 'img_set',)\
                        .filter(C_Status__name='ACTIVE', C_Setting__slug='lakefront', \
                                C_AskPrice__gte=2000000).order_by('-C_LstDate')[:6]

    context.update({
        'active': active, 'price_change':price_change,
        'lakefronts': lakefronts, 'modal_should_load':False
        })



    if not request.session.get('modal_has_loaded'):
        request.session['modal_has_loaded'] = True
        context['modal_should_load'] = True

    user_agent = request.META.get("HTTP_USER_AGENT")
    http_accept = request.META.get("HTTP_ACCEPT")

    if user_agent and http_accept:
        agent = mdetect.UAgentInfo(userAgent=user_agent, httpAccept=http_accept)
        is_tablet = agent.detectTierTablet()
        is_phone = agent.detectTierIphone()
        is_mobile = is_tablet or is_phone or agent.detectMobileQuick()

        if is_mobile:
            context['modal_should_load'] = False

    return render_to_response(template, context, context_instance=RequestContext(request))


def contact_us(request, template='contact_us.html', context={}):
    return render_to_response(template, context, context_instance=RequestContext(request))

def ajax_contact_us(request, context={}):
    if request.is_ajax():
        obj = dict(request.POST)
        form = ContactUsForm(request.POST)
        if form.is_valid():
            cleaned_data = form.cleaned_data
            subject = u'[CBLakeTahoe] Contact Us Submission'
            to = 'aardvark5678@gmail.com'
            from_email = settings.EMAIL_HOST_USER

            context['email'] = cleaned_data['email']
            context['name']  = cleaned_data['name']
            context['phone'] = cleaned_data['phone']
            context['message'] = cleaned_data['message']

            template_html = 'email/contact.html'
            template_text = strip_tags('email/contact.html')
            text_content = render_to_string(template_text, context)
            html_content = render_to_string(template_html, context)
            if isinstance(to, list):
                send_html_mail(subject, text_content, html_content, from_email, to, account=0)
            else:
                send_html_mail(subject, text_content, html_content, from_email, settings.EMAIL_RECIEVER, account=0)
            obj['status'] = True
        else:
            obj = dict(form.errors.items())
            obj['status'] = False
        return HttpResponse(simplejson.dumps(obj), mimetype='text/json')


def about(request, template='about.html', context={}):
    """
        GET about us page
    """
    context['seo_tags'] = {}
    context['seo_tags']['description'] = "We built this Lake Tahoe real estate site from the ground up to be different." \
      "We made sure to deliver more property data. We preview the properties for sale and we post our comments and photos." \
       "We\'re eager to earn your real estate business."
    return render_to_response(template, context, context_instance=RequestContext(request))

def our_opinions(request, template='our-opinions.html', context={}):
    """
        GET out opinion page
    """
    context['seo_tags'] = {}
    context['seo_tags']['description'] = "No fluff, active listings and solds, read our opinions and comments on the Lake Tahoe real estate listings."
    context['reviewed_photos'] = Listing.get_reviewed_listing(max_length=15, review_type='comments')
    return render_to_response(template, context, context_instance=RequestContext(request))

def manage_property(request, template='manage-property.html', context={}):
    """
        GET property management page
    """
    management = PropertyManagement.objects.latest('id')    
    context['management'] = management
    return render_to_response(template, context, context_instance=RequestContext(request))

def list_directory(request, template='laketahoe-directory.html', context={}):
    """
        list_directory    
    """
    context['all_directories'] = BusinessDirectory.objects.all()
    context['introduction_text'] = "From coordinating the ongoing seasonal maintenance for small projects like carpet cleaning and pine needles, to on-site caretakers and property managers, we coordinate and oversee the efforts on your behalf. Eyes and ears on your home year round. Great people, excellent service and a reasonable price."    
    return render_to_response(template, context, context_instance=RequestContext(request))

cblt/templates/about.html
{% extends 'base.html' %}

{% load humanize %}
{% load staticfiles %}
{% block breadcrumbs %}
&raquo;
<li>About Us</li>
{% endblock %}
{% block page_title %}You've never seen a real estate website like this{% endblock %}
{% block container %}
<div class='about-us'>
    <h1 class='page-header'>A Unique Resource for Truckee and Lake Tahoe Real Estate Information</h1>

    <div class='row'>
        <div class='content'>
            <div class='member span8' style='text-align:justify;'>
                <p>Determined to be the best resource for Truckee and Lake Tahoe real estate, we custom built our website (more importantly our business philosophy and our team) to excel where most fall short. We made a point to provide more stats and more property data.  We post photos and good honest opinions of properties for sale, we map things like how far the home is from the neighborhood trailheads.  Most importantly, we do it all with a focus on integrity and thus with passion.</p> 

                <p>I’ve been a real estate broker in the Lake Tahoe region since 1999. I’m 45 and I’m proud to say I was raised in the Pacific Northwest. My team shares my focus on ethics, effort, and community. We work hard, we play hard, we’re well respected, and we're proud of the people we are at our core. Our team shares a passion for the outdoors. Time spent outside recharges the batteries and the positive energy spills over into all areas of our lives. From cabins to historic estates, buyers and sellers, we appreciate the opportunity and we’re eager to get to work for you.</p>

                <p>Working with buyers has always been a major focus for me. These families are excited about finding a home in the Truckee and Lake Tahoe region. It’s fun to be around that excitement. It keeps us connected to the memories of when we first settled in Lake Tahoe. From modest cabins to luxury properties, we’re eager to share our experience to help buyers find their perfect home.</p>

                <p>For sellers, very few of our peers can match our exposure to buyers. We put a lot of effort into marketing to and working with buyers. From our custom built (buyer focused) websites, to the PR campaigns and the networking, the focused exposure we deliver is unique.  If you’re considering selling you home, we would love the opportunity to show you the difference.</p>               
                <hr>
                <p><i>Thank you!<br>
                I appreciate the opportunity!<br>
                Let us know what you think of the website!<br>
                <a href="mailto:tristan@cblaketahoe.com">Tristan@CBLakeTahoe.com</a></i></p>

            </div><!-- /.member -->
            <div class='member span4'>
                <img src="{% static 'img/photos/tristan_head_circle.png' %}" alt='Tristan Roberts'>
                <h2>Tristan Roberts</h2>
                <p>CBLakeTahoe.com</p>
            </div>

        </div><!-- /.content -->
    </div><!-- /.row -->
</div><!-- /.about-us -->
<hr/>
{% comment %}
<div class='row'>
    <div class='span6'>
        <h2>Our Mission</h2>
        <p>Morbi rhoncus, nisi eget molestie gravida, nunc turpis porttitor tortor, id sagittis eros magna sed arcu. In hac habitasse platea dictumst. Integer placerat gravida orci, in gravida massa dapibus nec. Nam commodo rhoncus urna, et imperdiet odio lacinia sodales. Morbi accumsan aliquet metus, ac malesuada quam rutrum et. Curabitur porttitor tincidunt lorem, id mollis dui fringilla sit amet. Mauris vitae risus nunc. Nunc pulvinar varius magna, sed scelerisque arcu varius vitae.</p>
        <p>Donec lobortis tincidunt justo et rhoncus. Etiam ac ligula a diam consectetur commodo vitae non ipsum. Etiam viverra leo at nunc sollicitudin hendrerit. Sed feugiat massa ac nisl dictum tempus sed quis nulla. Vivamus aliquam venenatis porta.<br>
            Quisque eget velit dictum orci luctus lacinia. Donec eget augue non sem</p>
        <p><a href='/contact-us' class='btn btn-primary'>Contact us</a>
        </p></div>
    <div class='span6'>
        <h2>Company presentation</h2>
        <iframe src='http://player.vimeo.com/video/61702922' width='500' height='281'></iframe><p><a href='http://vimeo.com/61702922'>EVERYBODY WANTS TO KILL BRUCE</a> from <a href='http://vimeo.com/user7408417'>Pierre-Alexandre Chauvat</a> on <a href='http://vimeo.com'>Vimeo</a>.</p>
    </div>
</div>
<div class='partners'>
    <h2 class='page-header'>Partners</h2>
    <div class='content'>
        <div class='partner'>
            <a href='http://logopond.com/gallery/detail/192115'>
                <img src="{% static 'img/photos/logo-sokolov.png' %}" alt='Logo'>
            </a>
        </div><!-- /.partner -->

        <div class='partner'>
            <a href='http://logopond.com/gallery/detail/191954'>
                <img src="{% static 'img/photos/logo-love-letters.png' %}" alt='Logo'>
            </a>
        </div><!-- /.partner -->

        <div class='partner'>
            <a href='http://logopond.com/gallery/detail/192592'>
                <img src="{% static 'img/photos/logo-royal-markt.png' %}" alt='Logo'>
            </a>
        </div><!-- /.partner -->

        <div class='partner'>
            <a href='http://logopond.com/gallery/detail/192905'>
                <img src="{% static 'img/photos/logo-shuba.png' %}" alt='Logo'>
            </a>
        </div><!-- /.partner -->

        <div class='partner'>
            <a href='http://logopond.com/gallery/detail/192394'>
                <img src="{% static 'img/photos/logo-sunsynk.png' %}" alt='Logo'>
            </a>
        </div><!-- /.partner -->
    </div><!-- /.content -->
</div><!-- /.partners-->
{% endcomment %}
{% endblock %}

cblt/templates/coming-soon.html
{% extends 'base.html' %}

{% load humanize %}

{% block container %}
<div class='not-found'>
    <strong>Soon</strong>
    <h1>We are currently working on this page.</h1>
    <hr/>
    <p>
        <a href='{% url 'home' %}'>return back</a>
    </p>
</div>
{% endblock %}

cblt/templates/contact_us.html
{% extends 'base.html' %}

{% load humanize %}

{% block breadcrumbs %}
&raquo;
<li>Contact Us</li>
{% endblock %}

{% block container %}
<div class='row'>
    <div class='span9'>
        <h1 class='page-header'>Contact us</h1>
        <iframe class='map contact-us-map' width='425' height='350' src='https://maps.google.com/maps?q=39.170745,-120.142012&amp;num=1&amp;ie=UTF8&amp;ll=39.170745,-120.142012&amp;spn=0.005448,0.011222&amp;t=m&amp;z=14&amp;output=embed'></iframe>

        <div class='row'>
            <div class='span3'>
                <h3 class='address'>Address</h3>
                <p class='content-icon-spacing'>
                    531 North Lake Blvd<br/>
                    Tahoe City, CA 96145<br/>
                    United States
                </p>
            </div>
            <div class='span3'>
                <h3 class='call-us'>Call us</h3>
                <p class='content-icon-spacing'>
                    530-580-8001
                </p>
            </div>
            <div class='span3'>
                <h3 class='email'>Email</h3>
                <p class='content-icon-spacing'>
                    <a href='mailto:roberts.tristan@gmail.com'>Tristan Roberts &amp; Associates</a><br/>
                    <!--Coldwell Banker Residential Brokerage<br/ -->
                    LIC#: 01259729
                </p>
            </div>
        </div>

        <h2>We'd love to hear from you!</h2>

        <form method='post' class='contact-form' action='?'>
            {% csrf_token %}
            <div id='error_message'>
            </div>
            <div class='name control-group'>
                <label class='control-label' for='inputContactName'>
                    Name
                    <span class='form-required' title='This field is required.'>*</span>
                </label>
                <div class='controls'>
                    <input type='text' id='id_name' name='name' value=''>
                </div><!-- /.controls -->
            </div><!-- /.control-group -->

            <div class='email control-group'>
                <label class='control-label' for='inputContactEmail'>
                    Email
                    <span class='form-required' title='This field is required.'>*</span>
                </label>
                <div class='controls'>
                    <input type='text' id='id_email' name='email' value=''>
                </div><!-- /.controls -->
            </div><!-- /.control-group -->

            <div class='phone control-group'>
                <label class='control-label' for='inputContactPhone'>
                    Phone
                </label>
                <div class='controls'>
                    <input type='text' id='id_phone' name='phone' value=''>
                </div><!-- /.controls -->
            </div><!-- /.control-group -->

            <div class='control-group'>
                <label class='control-label' for='inputContactMessage'>
                    Message
                    <span class='form-required' title='This field is required.'>*</span>
                </label>

                <div class='controls'>
                    <textarea id='id_message' name='message' value=''></textarea>
                </div><!-- /.controls -->
            </div><!-- /.control-group -->

            <div class='form-actions'>
                <input type='submit' id='contactUsSubmit' class='btn btn-primary arrow-right' value='Send'>
            </div><!-- /.form-actions -->
        </form>
    </div>

    <div class='sidebar span3'>
         <div class="mailchimp-newsletterform">
            <iframe src='http://eepurl.com/bEQuE5' frameborder='0'
            width='100%' height='1130' allowtransparency='true'>
            </iframe>
        </div>
        <div class='widget properties last'>
            <div class='title'>
                <h2 class='page-header link'><a href='{% url 'latest_listings' %}'>New Listings</a></h2>
            </div><!-- /.title -->

            <div class='content'>
                {% for listing in LATEST_PROPERTIES %}
                <div class='property sidebar-property'>
                    <div class='image'>
                        <a href='{{ listing.get_detailed_property_url }}'></a>
                        <img src='{{ listing.get_picture_url }}' alt=''>
                    </div><!-- /.image -->
                    <div class='wrapper'>
                        <div class='title'>
                            <h3>
                                <a href='{{ listing.get_detailed_property_url }}'>{{ listing.C_Address|truncatechars:'19' }}</a>
                            </h3>
                        </div><!-- /.title -->
                        <div class='location'>{{ listing.C_Community }}</div><!-- /.location -->
                        <div class='price'>${{ listing.C_AskPrice|floatformat|intcomma }}</div><!-- /.price -->
                    </div><!-- /.wrapper -->
                </div><!-- /.property -->
                {% endfor %}
            </div><!-- /.content -->
        </div><!-- /.properties -->
    </div>
</div>
{% endblock %}

cblt/templates/content_page.html
{% extends 'blog.html' %}

{% block breadcrumbs %}
&raquo;
<li><a href="{% url 'blog' %}">Blog</a></li> &raquo;
<li>{{ content.title }}</li>
{% endblock %}

{% block blog_content %}
<div class='properties-rows'>
    <div class='row'>
        {% if content.is_full_content%}
        <div class='property span9'>
            <div class='row'>
                <div class='body span8 margin-left10'>
                    <div class='title-price row'>
                        <div class='title span7'>
                            <h2><a href='#{{ content.title|slugify }}' name='#{{ content.title|slugify }}'>{{ content.title }}</a></h2>
                        </div><!-- /.title -->
                        <div class='price'>
                        </div><!-- /.price -->
                    </div><!-- /.title -->

                    <div class='location'>&nbsp;</div><!-- /.location -->
                    {% if content.content %}
                    <p>{{ content.content|safe }}</p>
                    {% endif %}
                    {% if content.gallery %}
                    <div id='gallery_{{ content.gallery.id }}' class='royalSlider rsDefault siteContentGallery'>
                        {% for image in content.gallery.photos.all %}
                            <a class='rsImg' href='{{ image.image.url }}'>
                                <img class='rsTmb lazy' width='56' height='56' src='{{ image.image.url }}'/>
                            </a>
                        {% endfor %}
                    </div>
                    {% endif %}
                </div><!-- /.body -->
            </div><!-- /.property -->
        </div>
        {% endif %}
    </div>
</div>
{% endblock %}